part of 'user_bloc.dart';

@freezed
class UserState with _$UserState {
  const factory UserState({
    int? isLoading,
    int? isLoadingP,
    int? isLoadingReg,
    String? authenticationMessage,
    String? eventMessage,
    String? registerFailedMessage,
    User? user,
    String? newPassword,
    int? isCode,
    File? cniImageAvant,
    File? cniImageArriere,
    File? cartegriseImage,
    int? isLoadingForgot,
    int? isUpdateUserImage,
    int? isCorrectCode,
    bool? successReset,
    bool? updating,
    TextEditingController? name,
    TextEditingController? email,
    TextEditingController? phone,
    TextEditingController? adress,
    TextEditingController? city,
    TextEditingController? numImpot,
    TextEditingController? numContribuable,
    TextEditingController? webSite,
    TextEditingController? country,
    TextEditingController? registreCommerce,
    TextEditingController? rccaAA,
    TextEditingController? nuiUser,
    TextEditingController? uaya,
  }) = _UserState;

  factory UserState.initial() => UserState(
        isCode: 0,
        updating: false,
        user: null,
        isCorrectCode: 0,
        successReset: false,
        cniImageAvant: null,
        cniImageArriere: null,
        cartegriseImage: null,
        isLoadingP: 0,
        isLoading: 0,
        isLoadingReg: 0,
        isUpdateUserImage: 0,
        name: TextEditingController(),
        email: TextEditingController(),
        phone: TextEditingController(),
        adress: TextEditingController(),
        city: TextEditingController(),
        numImpot: TextEditingController(),
        numContribuable: TextEditingController(),
        webSite: TextEditingController(),
        country: TextEditingController(),
        registreCommerce: TextEditingController(),
        nuiUser: TextEditingController(),
        rccaAA: TextEditingController(),
        uaya: TextEditingController(),
      );
}
